print("Create a character!")
name = input("What's his name?")
age = input("How old is He/she?")
powers = input("What powers He/She has?")
print("His/Her name is:", name)
print("His/Her age is:", age, "year/s")
print("His/Her powers are:", powers)